# Dockerfile
docker run -e  http://proxy.clermont-universite.fr:8080  -v /:/mnt  -it ubuntu:16.04 /bin/bash ???


docker pull ubuntu:16.04 en local.... # xenial
docker run -v /:/mnt  -it ubuntu:16.04 /bin/bash

# Mixte de ces dockerfile
https://github.com/replikation/docker_files_large/blob/master/plasflow/Dockerfile # bc d'erreurs 
https://github.com/pegi3s/dockerfiles/blob/master/plasflow/1.1.0/Dockerfile # plus performant

RUN apt-get update && apt-get install -y --no-install-recommends 
RUN apt-get clean
apt-get install -y wget
RUN apt-get install -y libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev


# install correct conda version for plasflow
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN Miniconda3-latest-Linux-x86_64.sh -b -p miniconda3

RUN conda init bash

Dans  /root/.bashrc, ajoute de : 

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<



Il faut se déconnecter !!!

ENV PATH /miniconda3/bin:$PATH  # export PATH=/miniconda3/bin:$PATH

# install plasflow
RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge
RUN conda create --name plasflow python=3.5
RUN conda activate plasflow
RUN conda install -c jjhelmus tensorflow=0.10.0rc0
RUN conda install plasflow -c smaegol
	# Non installé car pas dans la doc
					RUN conda install -c bioconda perl-bioperl perl-getopt-long
					# modify shebangs for bioperl
					RUN sed -i '1i#!/conda/bin/perl' /conda/bin/filter_sequences_by_length.pl


# Trop compliqué, départ d'un dockerfile basé sur plasflow
docker pull replikation/plasflow en local
 docker run -v /:/mnt  -it replikation/plasflow /bin/bash
 PlasFlow est opérationnel 3.72 Gb
 R version 3.4.1 installé
 
apt-get update
apt-get install -y hmmer
apt-get install -y prodigal
apt-get install -y ncbi-blast+


apt install r-base r-base-core r-recommended
R
install.packages("ade4")
install.packages("circlize")
install.packages("genoPlotR")
q()
# docker commit 537e6a84b51e plassuite:R 4.39GB


